/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerTelaPrincipal;
import javax.swing.JTextField;

/**
 *
 * @author jair
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private int ocupacao = 0;
    private int capacidade = 50;
    private int vagas;
    private final ControllerTelaPrincipal controller;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        controller = new ControllerTelaPrincipal(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonRemover = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();
        jLabelVagas = new javax.swing.JLabel();
        jLabelCapacidade = new javax.swing.JLabel();
        jLabelOcupacao = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldOcupacao = new javax.swing.JTextField();
        jTextFieldVagas = new javax.swing.JTextField();
        jTextFieldCapacidade = new javax.swing.JTextField();
        jMenuBarMenuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRemover.setBackground(new java.awt.Color(255, 0, 0));
        jButtonRemover.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.setBorderPainted(false);
        jButtonRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jButtonAdicionar.setBackground(new java.awt.Color(51, 255, 51));
        jButtonAdicionar.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.setBorderPainted(false);
        jButtonAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabelVagas.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        jLabelVagas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVagas.setText("Vagas:");
        jPanel1.add(jLabelVagas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabelCapacidade.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        jLabelCapacidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCapacidade.setText("Capacidade:");
        jPanel1.add(jLabelCapacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabelOcupacao.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        jLabelOcupacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOcupacao.setText("Ocupação:");
        jPanel1.add(jLabelOcupacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Controle de Lotação");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 40));

        jTextFieldOcupacao.setEditable(false);
        jTextFieldOcupacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldOcupacao.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jTextFieldOcupacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOcupacaoActionPerformed(evt);
            }
        });
        this.jTextFieldOcupacao.setText(String.valueOf(this.getOcupacao()));
        jPanel1.add(jTextFieldOcupacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 50, -1));

        jTextFieldVagas.setEditable(false);
        jTextFieldVagas.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVagas.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jTextFieldVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVagasActionPerformed(evt);
            }
        });
        this.jTextFieldVagas.setText(String.valueOf(this.getVagas()));
        jPanel1.add(jTextFieldVagas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 50, -1));

        jTextFieldCapacidade.setEditable(false);
        jTextFieldCapacidade.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCapacidade.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jTextFieldCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCapacidadeActionPerformed(evt);
            }
        });
        this.jTextFieldCapacidade.setText(String.valueOf(this.getCapacidade()));
        jPanel1.add(jTextFieldCapacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 390));

        jMenuBarMenuPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jMenu1.setText("Clientes");

        jMenuItem1.setText("Cadastros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Calcular IMC");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBarMenuPrincipal.add(jMenu1);

        jMenu2.setText("Usuario");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSair);

        jMenuBarMenuPrincipal.add(jMenu2);

        setJMenuBar(jMenuBarMenuPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed

        this.controller.LigSaída();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // Quando pressionado executa "remover"
        this.controller.remover();
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // Quando for precionado executa "adicionar"
        this.controller.adicionar();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jTextFieldOcupacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOcupacaoActionPerformed
        
    }//GEN-LAST:event_jTextFieldOcupacaoActionPerformed

    private void jTextFieldVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVagasActionPerformed
        
    }//GEN-LAST:event_jTextFieldVagasActionPerformed

    private void jTextFieldCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCapacidadeActionPerformed
        
    }//GEN-LAST:event_jTextFieldCapacidadeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.controller.Lig1();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.controller.Lig2();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabelCapacidade;
    private javax.swing.JLabel jLabelOcupacao;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVagas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarMenuPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCapacidade;
    private javax.swing.JTextField jTextFieldOcupacao;
    private javax.swing.JTextField jTextFieldVagas;
    // End of variables declaration//GEN-END:variables

    public int getOcupacao() {
        return ocupacao;
    }

    public void setOcupacao(int ocupacao) {
        this.ocupacao = ocupacao;
    }

    public int getCapacidade() {
        return capacidade;
    }

    public void setCapacidade(int capacidade) {
        this.capacidade = capacidade;
    }

    public int getVagas() {
        return this.getCapacidade() - this.getOcupacao();
    }

    public void setVagas(int vagas) {
        this.vagas = vagas;
    }

    public JTextField getjTextFieldCapacidade() {
        return jTextFieldCapacidade;
    }

    public void setjTextFieldCapacidade(JTextField jTextFieldCapacidade) {
        this.jTextFieldCapacidade = jTextFieldCapacidade;
    }

    public JTextField getjTextFieldOcupacao() {
        return jTextFieldOcupacao;
    }

    public void setjTextFieldOcupacao(JTextField jTextFieldOcupacao) {
        this.jTextFieldOcupacao = jTextFieldOcupacao;
    }

    public JTextField getjTextFieldVagas() {
        return jTextFieldVagas;
    }

    public void setjTextFieldVagas(JTextField jTextFieldVagas) {
        this.jTextFieldVagas = jTextFieldVagas;
    }
    
    
}
