package view;

import control.ControllerIMC;
import javax.swing.JOptionPane;

/**
 *
 * @author jair
 */
public class TelaImc extends javax.swing.JFrame {
    String A,b;
    float x, y;
    private final ControllerIMC controller;
    /**
     * Creates new form TelaCadastro
     */
    
    public TelaImc(){
        initComponents();
        controller = new ControllerIMC(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelImc = new javax.swing.JLabel();
        jLabelAltura = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        lblIMC = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jTextFieldAltura = new javax.swing.JTextField();
        jButtonCalcular1 = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelStatus1 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de IMC");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStatus.setBackground(new java.awt.Color(255, 255, 255));
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, 20));

        jLabelTitulo.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Calculadora de IMC");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabelTipo.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipo.setText("Dica:");
        jPanel1.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabelImc.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelImc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImc.setText("IMC:");
        jPanel1.add(jLabelImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabelAltura.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelAltura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAltura.setText("Altura(m):");
        jPanel1.add(jLabelAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabelPeso.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelPeso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPeso.setText("Peso(kg):");
        jPanel1.add(jLabelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblIMC.setBackground(new java.awt.Color(255, 255, 255));
        lblIMC.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 80, 20));

        jTextFieldPeso.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jTextFieldPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 80, -1));

        jTextFieldAltura.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jTextFieldAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlturaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 80, -1));

        jButtonCalcular1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButtonCalcular1.setText("Calcular");
        jButtonCalcular1.setBorderPainted(false);
        jButtonCalcular1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcular1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCalcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 90, -1));

        jButtonSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabelStatus1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelStatus1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus1.setText("Status:");
        jPanel1.add(jLabelStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblTipo.setBackground(new java.awt.Color(255, 255, 255));
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 190, 20));

        jButtonLimpar.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setBorderPainted(false);
        jButtonLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 109, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcular1ActionPerformed
        if (ChecarNumeros()){
            lblIMC.setText(""+controller.getIMC());
            lblStatus.setText(""+controller.getStatus());
            lblTipo.setText(""+controller.getTipo());
        }
    }//GEN-LAST:event_jButtonCalcular1ActionPerformed

    public boolean ChecarNumeros(){
        if(controller.getCheckEmpty(jTextFieldPeso.getText(),jTextFieldAltura.getText())){
            JOptionPane.showMessageDialog(this, "Campos Vazios","ERROR", 0);
            return false;
        }else{
            if(controller.getCheckIsNum()){
                return true;
            }else{
                JOptionPane.showMessageDialog(this,"Somente Números","ERROR",0);
                return false;
            }
        }
    }

    private void jTextFieldAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlturaActionPerformed

    private void jTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldPeso.setText("");
        jTextFieldAltura.setText("");
        lblIMC.setText(""+controller.getIMC());
        lblStatus.setText(""+controller.getStatus());
        lblTipo.setText(""+controller.getTipo());
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
         this.controller.LigSaída1();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaImc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular1;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelImc;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelStatus1;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables

}