/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerCadastro;
import javax.swing.JTextField;
import model.Cliente;

/**
 *
 * @author jair
 */
public class TelaCadastro extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaVisualCadastro
     */
    //ControllerCadastro tabelaClientes = new ControllerCadastro();
    
    private final ControllerCadastro tabelaClientes;
    
    
    public TelaCadastro() {
        initComponents();
        tabelaClientes = new ControllerCadastro(this);
        jTableCadastro.setModel(tabelaClientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonCadastro = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelAltura = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Cadastros");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jButtonSair.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        jButtonCadastro.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButtonCadastro.setText("Cadastrar");
        jButtonCadastro.setBorderPainted(false);
        jButtonCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jButtonAtualizar.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.setBorderPainted(false);
        jButtonAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jButtonRemover.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.setBorderPainted(false);
        jButtonRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jTextFieldNome.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 220, -1));

        jLabelNome.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome:");
        jPanel1.add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email:");
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jTextFieldEmail.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 220, -1));

        jLabelAltura.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelAltura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAltura.setText("Altura(cm):");
        jPanel1.add(jLabelAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 80, -1));

        jTextFieldAltura.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jTextFieldAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFieldAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 70, -1));

        jTextFieldPeso.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jTextFieldPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFieldPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 60, -1));

        jLabelPeso.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelPeso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPeso.setText("Peso(kg):");
        jPanel1.add(jLabelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jTextFieldCpf.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 220, -1));

        jLabelCpf.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelCpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCpf.setText("CPF:");
        jPanel1.add(jLabelCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jTableCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "CPF", "Altura", "Peso"
            }
        ));
        jScrollPane1.setViewportView(jTableCadastro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 580, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.tabelaClientes.LigSaída2();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        Cliente cliente = new Cliente();
        cliente.setCpf(Integer.parseInt(getjTextFieldCpf().getText()));
        cliente.setNome(getjTextFieldNome().getText());
        cliente.setEmail(getjTextFieldEmail().getText());
        cliente.setPeso(Float.parseFloat(getjTextFieldPeso().getText()));
        cliente.setAltura(Float.parseFloat(getjTextFieldAltura().getText()));
        
        tabelaClientes.adicionarLinha(cliente);
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        if (jTableCadastro.getSelectedRow() != -1) {
            tabelaClientes.setValueAt(jTextFieldCpf.getText(), jTableCadastro.getSelectedRow(), 0);
            tabelaClientes.setValueAt(jTextFieldNome.getText(), jTableCadastro.getSelectedRow(), 1);
            tabelaClientes.setValueAt(jTextFieldEmail.getText(), jTableCadastro.getSelectedRow(), 2);
            tabelaClientes.setValueAt(jTextFieldPeso.getText(), jTableCadastro.getSelectedRow(), 3);
            tabelaClientes.setValueAt(jTextFieldAltura.getText(), jTableCadastro.getSelectedRow(), 4);
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        if (jTableCadastro.getSelectedRow() != -1) {
            tabelaClientes.removerLinha(jTableCadastro.getSelectedRow());
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastro;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPeso;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextFieldAltura() {
        return jTextFieldAltura;
    }

    public void setjTextFieldAltura(JTextField jTextFieldAltura) {
        this.jTextFieldAltura = jTextFieldAltura;
    }

    public JTextField getjTextFieldCpf() {
        return jTextFieldCpf;
    }

    public void setjTextFieldCpf(JTextField jTextFieldCpf) {
        this.jTextFieldCpf = jTextFieldCpf;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public void setjTextFieldEmail(JTextField jTextFieldEmail) {
        this.jTextFieldEmail = jTextFieldEmail;
    }

    public JTextField getjTextFieldNome() {
        return jTextFieldNome;
    }

    public void setjTextFieldNome(JTextField jTextFieldNome) {
        this.jTextFieldNome = jTextFieldNome;
    }

    public JTextField getjTextFieldPeso() {
        return jTextFieldPeso;
    }

    public void setjTextFieldPeso(JTextField jTextFieldPeso) {
        this.jTextFieldPeso = jTextFieldPeso;
    }
    
}
